<style type="text/css"><!--
    h1, h2, h3{ color:#515D64; }
    h3{ font-size:16px; }
    .message{ font-size:17px; }
    .red{ color:#f60; }
//--></style>

<p style="margin:40px 0px 40px -32px">
    <a href="/"><img src="/public/i/logo.png" alt=""/></a>
</p>

<h1><?= $this->message ?></h1>

<? if (isset($this->exception)) : ?>

    <p class="message"><span class="red">Debug message&nbsp;&nbsp;|</span>&nbsp;&nbsp;<?= $this->exception->getMessage() ?></p>

    <h3>Stack trace</h3>
    <pre style="overflow:auto"><?= $this->exception->getTraceAsString() ?></pre>

    <h3>Request Parameters</h3>
    <pre style="overflow:auto"><?= var_export($this->request->getParams(), true) ?></pre>

<? endif ?>
