<!doctype html>
<html>
<head>
    <?= $this->headTitle()->setSeparator(' / ') ?>
    <meta charset="utf-8"/>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
    <?= $this->headScript() ?>
    <?= $this->headLink() ?>
    <script src="/public/js/main.js"></script>
    <link rel="stylesheet" type="text/css" href="/public/css/main.css" />
</head>
<body>

    <?= $this->layout()->content ?>

</body>
</html>